### ISSUE TITLE
Consider adding an option to Kexec latest Linux kernel instead of full reboot

### ISSUE THREAD

**Issue by DrMattChristian** [agross/dnf-automatic-restart#12]
Your project says restart machine but I'm wondering if you'd consider adding an option to Kexec the latest Linux kernel instead of a full reboot?

On physical machines, [Kexec](https://wiki.archlinux.org/index.php/Kexec) is often faster/quicker than restarting since [Kexec](https://access.redhat.com/solutions/2351931) does not need to re-initialize the hardware, BIOS/UEFI POST, etc.

On virtual machines (VMs), the time difference between Kexec and reboot is less pronounced but can still save some time.

I wrote a quick shell script I called [auto-kexec](https://github.com/DrMattChristian/auto-kexec) to automatically Kexec on non-dnf RPM-based systems like RHEL 6 and 7.

I can help with implementing on a new PR, reviewing changes or testing Kexec code, but I wanted to run this idea by you first.

**Comment by agross** [comment]
Hi @DrMattChristian,

Thank you for your suggestion! I knew that reloading the kernel was somehow possible but never researched how it could be done.

> if you'd consider adding an option to Kexec

I would consider that as an option to rebooting, i.e. have the user choose to reboot or your suggested change to kexec (perhaps using an `-x` option).

I'd appreciate if you could submit a PR.
