### ISSUE TITLE
dnf-automatic no more

### ISSUE THREAD

**Issue by da2x** [agross/dnf-automatic-restart#2]
dnf-automatic.timer has been split up into several services since version 2.0. See [dnf-automatic documentation](https://github.com/rpm-software-management/dnf/blob/master/doc/automatic.rst) or my [tutorial](https://ctrl.blog/entry/how-to-dnf-automatic). You may want to update your documentation and script, (possibly even [submit it upstream](https://github.com/rpm-software-management/dnf/tree/master/etc/systemd)?)

**Comment by agross** [comment]
@da2x Thanks for the heads up!
