### ISSUE TITLE
disable automatic restart

### ISSUE THREAD

**Issue by CaptainTyphoo** [agross/dnf-automatic-restart#4]
Is it possible to configure dnf-automatic-restart to only restart the services which need to be restarted and not restart the system when an update of the kernel or systemd was installed. I'm asking because my server has an encrypted root filesystem and would therefore not come back up on its own.

**Comment by agross** [comment]
Hi,

Currently that's not supported by the script. One solution would be to add a new switch `-d` to disable automatics reboots altogether. I'll take pull requests 😉

**Comment by CaptainTyphoo** [comment]
Thank you for your quick response! I just created a pull request (It's my first one, so I'm very open for feedback :smiley:)

**Comment by agross** [comment]
Closed by #5
