### ISSUE TITLE
Does not reboot on Fedora 27

### ISSUE THREAD

**Issue by MichaelRiss** [agross/dnf-automatic-restart#6]
Hello Alexander,

I'm a happy user of `dnf-automatic-restart`. However, lately I observe that after kernel updates the reboot does not happen and I think I know why:
- `tracer` communicates what needs to be done with its exit codes, see [here](https://github.com/FrostyX/tracer/blob/4487cddfedbaf2b02c7bd3cfdf66420b2e2e36ab/tracer/controllers/default.py#L119). These are in general != 0.
- `dnf-automatic-restart` uses `set -euo pipefail` to immediately stop when a command fails, i.e. its exit code is != 0.

Together that means that the execution of the `dnf-automatic-restart` script stops at [line 159](https://github.com/agross/dnf-automatic-restart/blob/8e5ac0c79abb2976496d2726873f17dd46eebef3/dnf-automatic-restart#L159) after the pipe execution has been finished and before the section dealing with rebooting the system gets executed.

That's the situation on my Fedora 27 system. On other systems the situation may be different. What's your take on it?

Cheers,
Michi

**Comment by agross** [comment]
Many thanks for reporting and sorting it out. I guess I'm not on top of my Fedora server maintenance lately ;-)
